### PR TITLE
Landing hut zooming

### PR DESCRIPTION
**Pull request by Josh-Tan-20-09-13**
Read Title

### CODE REVIEW

**Comment by abijitj** [comment]
That looks pretty good. Thanks for doing it so quickly!

The pixelated entrance is a bit weird but that's hard to solve. Maybe we could zoom in till the entrance completely encompasses the screen? Or we could manually overlay something over it??

Also, would it be possible to zoom more "directly" into the entrance?

**Comment by bimai25** [comment]
This looks really good! One comment, after you enter the hut and then click the back button to go back to the landing page, the background does this slight reset to its original position. Was this intentional and is it possible to avoid?

**Review by bimai25 — COMMENTED** [review]
see above comment

**Comment by bimai25** [comment]
> > This looks really good! One comment, after you enter the hut and then click the back button to go back to the landing page, the background does this slight reset to its original position. Was this intentional and is it possible to avoid?
> 
> I do not see this adjustment when hitting both the 'back' button and the back button on the web browser.

It may just be a Mac thing maybe then, not a big deal

**Pull request merged**
