### PR TITLE
Add landing page tests and install jest + puppeteer in source dir

### PR DESCRIPTION
**Pull request by abijitj**
1. npm installed jest and puppeteer in the source dir (using the same command from Lab 8)
2. Created puppeteer tests for the landing page. 

Note, we likely don't need unit tests (jest) for the landing page as there is very little backend functionality to test.

### CODE REVIEW

**Comment by nakulnandhakumar** [comment]
I think we need to gitignore the node_modules file

**Comment by nakulnandhakumar** [comment]
Also do we need to have it in our repo? It is triggering the linter and we should either find out how to suppress that or see if we can remove it

**Comment by bimai25** [comment]
i can adjust the workflow to ignore the testing files

**Comment by bimai25** [comment]
i'm going to merge the pull request (so i have a reference to how testing is being ran) and then I'll manually delete the node_modules folder. i added node_modules to the gitignore in main so hopefully this problem is avoided in the future

**Comment by bimai25** [comment]
@abijitj can you add node_modules/ to your git ignore and then create another pull request?

**Comment by abijitj** [comment]
> @abijitj can you add node_modules/ to your git ignore and then create another pull request?

Will do.

**Pull request merged**
