### PR TITLE
Delete individual fortune

### PR DESCRIPTION
**Pull request by nakulnandhakumar**
button needs to be styled

### CODE REVIEW

**Comment by abijitj** [comment]
The functionality looks good to me. But for the documentation, could you add a file header to your js file? The style guide has a format. 

Thanks

**Review by abijitj — CHANGES_REQUESTED** [review]
See the previous comment above.

**Comment by nakulnandhakumar** [comment]
Yeah sure will do. Where is the style guide?

**Comment by abijitj** [comment]
> Yeah sure will do. Where is the style guide?

[Here](https://github.com/cse110-sp23-group4/cse110-sp23-group4/blob/main/specs/fortune-telling-docs/jsdocs-style-guide.md)

**Review by ebayraktaroglu — CHANGES_REQUESTED** [review]
The functionality looks good, but you probably need to write some sort of documentation for the deleteFortune(fortuneIndex) function.

**Comment by nakulnandhakumar** [comment]
finished the documentation for the function
added file header for saved-readings-script

**Comment by ebayraktaroglu** [comment]
> The functionality looks good, but you probably need to write some sort of documentation for the deleteFortune(fortuneIndex) function.

I'm not sure how important it is, but there is a small typo in the function description: "We pass the index of the fortune that is has in the localstorage array and splice the array ti remove that one index," where you wrote 'ti' instead of 'to.'

**Pull request merged**
