### PR TITLE
Add github action for unit tests and e2e testing

### PR DESCRIPTION
**Pull request by OutisNoMore**
Setup github action for testing with jest and puppeteer.

### CODE REVIEW

**Comment by OutisNoMore** [comment]
Right now checks on push to any branch, for testing unit tests, and pull request to main

**Comment by abijitj** [comment]
Can the tests folder be moved into the source directory? Instead of source/prototyping? That makes more sense to me. But this is also fine if you all think that's better.

**Comment by bimai25** [comment]
i agree, i think we should move the tests into source

we will eventually have to move all the files from the prototyping directory to the fortune telling directory

**Review by bimai25 — COMMENTED** [review]
see above comment

**Comment by OutisNoMore** [comment]
test folders have been moved

**Pull request merged**
